import type { CanonicalAction, NegotiationState, Package, ScenarioDefinition } from '@arena/contracts';
import { S1, S2, acknowledge, argument, offer, pressure, question, supplyTerms, walkAway, workloadTerms } from '../src/index.ts';

export type GoldenTrace = {
  id: string; scenario: ScenarioDefinition; actions: CanonicalAction[];
  expected: { phase: NegotiationState['phase']; turns: number; trust?: number; tension?: number; credits?: number; discount?: number; aspiration?: number;
    terms: Package | null; utilities: [number, number] | null; family: 'MUTUAL_GAIN' | 'ACCEPTABLE_PARTIAL' | 'POOR_AGREEMENT' | 'NO_AGREEMENT'; events: string[] };
};
export const s1Prefix = () => [question('logistics'), question('payment'), acknowledge('cashflow-need'), argument('logistics-argument')];
export const s2Prefix = () => [question('priorities'), question('resources'), acknowledge('report-deferrable'), argument('resource-argument')];
export const GOLDENS: GoldenTrace[] = [
  { id: 'GS1', scenario: S1, actions: [...s1Prefix(), offer(supplyTerms(95, 'split40at7_rest14', 50))], expected: { phase: 'agreed', turns: 5, trust: 68, credits: 5, discount: 2, aspiration: 22, terms: supplyTerms(95, 'split40at7_rest14', 50), utilities: [64, 27], family: 'MUTUAL_GAIN', events: ['fact_disclosed', 'grounded_argument_applied', 'agreement_reached'] } },
  { id: 'GS2', scenario: S1, actions: [question('logistics'), question('payment'), acknowledge('logistics-saving'), argument('logistics-argument'), acknowledge('cashflow-need'), argument('cashflow-argument'), offer(supplyTerms(105, 'all7', 50))], expected: { phase: 'agreed', turns: 7, trust: 78, credits: 5, discount: 2, aspiration: 21, terms: supplyTerms(105, 'all7', 50), utilities: [59, 21], family: 'ACCEPTABLE_PARTIAL', events: ['grounded_argument_applied', 'agreement_reached'] } },
  { id: 'GS3', scenario: S1, actions: [offer(supplyTerms(90, 'all7', 0)), pressure(), pressure(), pressure(), pressure()], expected: { phase: 'opponent_walkaway', turns: 5, terms: null, utilities: null, family: 'NO_AGREEMENT', events: ['offer_rejected_aspiration', 'tension_warning', 'opponent_walkaway'] } },
  { id: 'GS4', scenario: S1, actions: [...s1Prefix(), offer(supplyTerms(110, 'all7', 50))], expected: { phase: 'agreed', turns: 5, trust: 68, credits: 5, discount: 0, aspiration: 24, terms: supplyTerms(110, 'all7', 50), utilities: [54, 26], family: 'POOR_AGREEMENT', events: ['agreement_reached'] } },
  { id: 'GS5', scenario: S1, actions: [question('payment'), offer(supplyTerms(115, 'all7', 50))], expected: { phase: 'agreed', turns: 2, trust: 54, credits: 2, discount: 0, aspiration: 31, terms: supplyTerms(115, 'all7', 50), utilities: [49, 31], family: 'POOR_AGREEMENT', events: ['agreement_reached'] } },
  { id: 'GS6', scenario: S1, actions: [...Array.from({ length: 7 }, () => question('logistics')), offer(supplyTerms(90, 'all7', 0))], expected: { phase: 'round_limit', turns: 8, trust: 54, credits: 2, terms: null, utilities: null, family: 'NO_AGREEMENT', events: ['offer_rejected_aspiration', 'round_limit'] } },
  { id: 'GS7', scenario: S1, actions: [...s1Prefix(), offer(supplyTerms(90, 'split40at7_rest14', 50))], expected: { phase: 'agreed', turns: 5, trust: 68, credits: 5, discount: 2, aspiration: 22, terms: supplyTerms(90, 'split40at7_rest14', 50), utilities: [69, 22], family: 'MUTUAL_GAIN', events: ['agreement_reached'] } },
  { id: 'GT1', scenario: S2, actions: [...s2Prefix(), offer(workloadTerms('full', 2, 1, 1))], expected: { phase: 'agreed', turns: 5, trust: 68, credits: 5, discount: 2, aspiration: 27, terms: workloadTerms('full', 2, 1, 1), utilities: [47, 30], family: 'MUTUAL_GAIN', events: ['resource_authorized', 'agreement_reached'] } },
  { id: 'GT2', scenario: S2, actions: [question('resources'), acknowledge('helper-available'), offer(workloadTerms('core', 2, 1, 0))], expected: { phase: 'agreed', turns: 3, trust: 60, credits: 3, discount: 0, aspiration: 33, terms: workloadTerms('core', 2, 1, 0), utilities: [32, 36], family: 'ACCEPTABLE_PARTIAL', events: ['agreement_reached'] } },
  { id: 'GT3', scenario: S2, actions: [offer(workloadTerms('full', 2, 0, 0)), pressure(), acknowledge('capacity-bound'), question('priorities'), question('resources'), acknowledge('helper-available'), argument('priority-argument'), offer(workloadTerms('full', 2, 1, 1))], expected: { phase: 'agreed', turns: 8, trust: 59, credits: 5, discount: 2, aspiration: 28, terms: workloadTerms('full', 2, 1, 1), utilities: [47, 30], family: 'MUTUAL_GAIN', events: ['offer_rejected_physical', 'counteroffer_created', 'agreement_reached'] } },
  { id: 'GT4', scenario: S2, actions: [walkAway()], expected: { phase: 'player_walkaway', turns: 1, terms: null, utilities: null, family: 'NO_AGREEMENT', events: ['player_walkaway'] } },
  { id: 'GT5', scenario: S2, actions: [offer(workloadTerms('core', 2, 1, 0)), question('resources'), acknowledge('helper-available'), offer(workloadTerms('core', 2, 1, 0))], expected: { phase: 'agreed', turns: 4, trust: 60, credits: 2, discount: 0, aspiration: 35, terms: workloadTerms('core', 2, 1, 0), utilities: [32, 36], family: 'ACCEPTABLE_PARTIAL', events: ['counteroffer_created', 'fact_disclosed', 'agreement_reached'] } },
  { id: 'GT6', scenario: S2, actions: [...s2Prefix(), offer(workloadTerms('core', 5, 0, 0))], expected: { phase: 'agreed', turns: 5, trust: 68, credits: 5, discount: 0, aspiration: 29, terms: workloadTerms('core', 5, 0, 0), utilities: [20, 34], family: 'POOR_AGREEMENT', events: ['agreement_reached'] } },
];
